CREATE CREDENTIAL [STORAGE-ENDPOINT]
    WITH IDENTITY = 'SHARED ACCESS SIGNATURE'
    SECRET = '<SAS TOKEN>'
GO

BACKUP DATABSE <DATABASE-NAME>
    TO URL = '[STORAGE-ENDPOINT]/FILENAME.BAK'
WITH CHECKSUM